### ISSUE TITLE
no superclass for java.lang.Object when processing 'subspace' app

### ISSUE THREAD

**Issue by webyrd** [Ucombinator/shimple-analyzer#4]
Given this bash script,

```
JAAM_SCRIPT=~/github/jaam/jaam.sh
CHALLENGE_PROGRAM_DIRECTORY=/Users/webyrd/STAC/stac_engagement_2_release_v1.0/Challenge_Programs_v2.0

printf "processing subspace...\n"
time nice $JAAM_SCRIPT --classpath $CHALLENGE_PROGRAM_DIRECTORY/subspace/challenge_program/lib/Subspace-1.0.jar:$CHALLENGE_PROGRAM_DIRECTORY/subspace/challenge_program/lib/activation-1.1.1.jar:$CHALLENGE_PROGRAM_DIRECTORY/subspace/challenge_program/lib/jsr305-1.3.9.jar:$CHALLENGE_PROGRAM_DIRECTORY/subspace/challenge_program/lib/mail-1.4.4.jar:$CHALLENGE_PROGRAM_DIRECTORY/subspace/challenge_program/lib/nanohttpd-2.1.0.jar:$CHALLENGE_PROGRAM_DIRECTORY/subspace/challenge_program/lib/slf4j-api-1.6.1.jar:$CHALLENGE_PROGRAM_DIRECTORY/subspace/challenge_program/lib/slf4j-simple-1.6.1.jar --class com.example.subspace.Main --method main > subspace.out
printf "\ndone!\n\n"
```

the analyzer reliably crashes with this output:

```
processing subspace...
Exception in thread "main" java.lang.RuntimeException: no superclass for java.lang.Object
    at soot.SootClass.getSuperclass(SootClass.java:762)
    at org.ucombinator.jaam.State.overrides$1(Main.scala:849)
    at org.ucombinator.jaam.State.org$ucombinator$jaam$State$$dispatch$1(Main.scala:859)
    at org.ucombinator.jaam.State$$anonfun$handleInvoke$1.apply(Main.scala:969)
    at org.ucombinator.jaam.State$$anonfun$handleInvoke$1.apply(Main.scala:965)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.Set$Set2.foreach(Set.scala:94)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
    at scala.collection.SetLike$class.map(SetLike.scala:93)
    at scala.collection.AbstractSet.map(Set.scala:47)
    at org.ucombinator.jaam.State.handleInvoke(Main.scala:965)
    at org.ucombinator.jaam.State.true_next(Main.scala:1114)
    at org.ucombinator.jaam.State.next(Main.scala:1020)
    at org.ucombinator.jaam.System$.next(Main.scala:1247)
    at org.ucombinator.jaam.Main$.defaultMode(Main.scala:1340)
    at org.ucombinator.jaam.Main$.main(Main.scala:1310)
    at org.ucombinator.jaam.Main.main(Main.scala)

real    0m3.523s
user    0m11.602s
sys 0m0.635s

done!
```

**Comment by peteraldous** [comment]
I don't see where $CHAL is defined. That aside, it seems likely that some
sort of type lookup or method dispatch routine is failing. Maybe no method
is defined where it needs to be? It might be that there are special cases
in the JVM for methods like Object.clone() or for an Array's methods (an
array is an Object) that won't be found in any bytecode anywhere.
